call scalaapi#package('scala.text', '', '[p]', [], [])
call scalaapi#object('DocBreak', 'scala.text', '[o]', ['Document', 'Product', 'Serializable'], [])
call scalaapi#object('DocNil', 'scala.text', '[o]', ['Document', 'Product', 'Serializable'], [])
call scalaapi#object('Document', 'scala.text', '[o]', [], [])
call scalaapi#class('Document', 'scala.text', '[c]', [], [])
