call scalaapi#package('scala.collection.concurrent', '', '[p]', '', [])
call scalaapi#trait('Map', 'scala.collection.concurrent', '[t]', '[A, B]', [])
call scalaapi#class('TrieMap.MangledHashing', 'scala.collection.concurrent', '[c]', '[K]', [])
call scalaapi#object('TrieMap', 'scala.collection.concurrent', '[o]', '', [])
call scalaapi#class('TrieMap', 'scala.collection.concurrent', '[c]', '[K, V]', [])
