call scalaapi#package('scala.util.hashing', '', '[p]', '', [])
call scalaapi#object('ByteswapHashing', 'scala.util.hashing', '[o]', '', [])
call scalaapi#class('ByteswapHashing', 'scala.util.hashing', '[c]', '[T]', [])
call scalaapi#class('Hashing.Default', 'scala.util.hashing', '[c]', '[T]', [])
call scalaapi#object('Hashing', 'scala.util.hashing', '[o]', '', [])
call scalaapi#trait('Hashing', 'scala.util.hashing', '[t]', '[T]', [])
call scalaapi#class('MurmurHash3.ArrayHashing', 'scala.util.hashing', '[c]', '[T]', [])
call scalaapi#object('MurmurHash3', 'scala.util.hashing', '[o]', '', [])
