call scalaapi#package('scala.beans', '', '[p]', [], [])
call scalaapi#class('BeanDescription', 'scala.beans', '[c]', ['Annotation'], [])
call scalaapi#class('BeanDisplayName', 'scala.beans', '[c]', ['Annotation'], [])
call scalaapi#class('BeanInfo', 'scala.beans', '[c]', ['Annotation'], [])
call scalaapi#class('BeanInfoSkip', 'scala.beans', '[c]', ['Annotation'], [])
call scalaapi#class('BeanProperty', 'scala.beans', '[c]', ['Annotation', 'StaticAnnotation'], [])
call scalaapi#class('BooleanBeanProperty', 'scala.beans', '[c]', ['Annotation', 'StaticAnnotation'], [])
call scalaapi#class('ScalaBeanInfo', 'scala.beans', '[c]', [], [])
