call scalaapi#package('scala.util.hashing', '', '[p]', [], [])
call scalaapi#object('ByteswapHashing', 'scala.util.hashing', '[o]', ['Serializable'], [])
call scalaapi#class('ByteswapHashing', 'scala.util.hashing', '[c]', ['Hashing'], [])
call scalaapi#class('Hashing.Default', 'scala.util.hashing', '[c]', ['Hashing'], [])
call scalaapi#object('Hashing', 'scala.util.hashing', '[o]', ['Serializable'], [])
call scalaapi#trait('Hashing', 'scala.util.hashing', '[t]', ['Serializable'], [])
call scalaapi#class('MurmurHash3.ArrayHashing', 'scala.util.hashing', '[c]', ['Hashing', 'Array'], [])
call scalaapi#object('MurmurHash3', 'scala.util.hashing', '[o]', [], [])
