call scalaapi#package('scala.collection.convert', '', '[p]', [], [])
call scalaapi#trait('DecorateAsJava', 'scala.collection.convert', '[t]', [], [])
call scalaapi#trait('DecorateAsScala', 'scala.collection.convert', '[t]', [], [])
call scalaapi#object('WrapAsJava', 'scala.collection.convert', '[o]', ['WrapAsJava'], [])
call scalaapi#trait('WrapAsJava', 'scala.collection.convert', '[t]', [], [])
call scalaapi#object('WrapAsScala', 'scala.collection.convert', '[o]', ['WrapAsScala'], [])
call scalaapi#trait('WrapAsScala', 'scala.collection.convert', '[t]', [], [])
call scalaapi#object('Wrappers', 'scala.collection.convert', '[o]', ['Serializable'], [])
