call scalaapi#package('scala.ref', '', '[p]', '', [])
call scalaapi#class('PhantomReference', 'scala.ref', '[c]', '[+T <: AnyRef]', [])
call scalaapi#trait('Reference', 'scala.ref', '[t]', '[+T <: AnyRef]', [])
call scalaapi#class('ReferenceQueue', 'scala.ref', '[c]', '[+T <: AnyRef]', [])
call scalaapi#trait('ReferenceWrapper', 'scala.ref', '[t]', '[+T <: AnyRef]', [])
call scalaapi#class('SoftReference', 'scala.ref', '[c]', '[+T <: AnyRef]', [])
call scalaapi#object('WeakReference', 'scala.ref', '[o]', '', [])
call scalaapi#class('WeakReference', 'scala.ref', '[c]', '[+T <: AnyRef]', [])
