call scalaapi#package('scala.ref', '', '[p]', [], [])
call scalaapi#class('PhantomReference', 'scala.ref', '[c]', ['ReferenceWrapper'], [])
call scalaapi#trait('Reference', 'scala.ref', '[t]', [], [])
call scalaapi#class('ReferenceQueue', 'scala.ref', '[c]', [], [])
call scalaapi#trait('ReferenceWrapper', 'scala.ref', '[t]', ['Reference', 'Proxy'], [])
call scalaapi#class('SoftReference', 'scala.ref', '[c]', ['ReferenceWrapper'], [])
call scalaapi#object('WeakReference', 'scala.ref', '[o]', [], [])
call scalaapi#class('WeakReference', 'scala.ref', '[c]', ['ReferenceWrapper'], [])
