call scalaapi#package('scala.beans', '', '[p]', '', [])
call scalaapi#class('BeanDescription', 'scala.beans', '[c]', '', [])
call scalaapi#class('BeanDisplayName', 'scala.beans', '[c]', '', [])
call scalaapi#class('BeanInfo', 'scala.beans', '[c]', '', [])
call scalaapi#class('BeanInfoSkip', 'scala.beans', '[c]', '', [])
call scalaapi#class('BeanProperty', 'scala.beans', '[c]', '', [])
call scalaapi#class('BooleanBeanProperty', 'scala.beans', '[c]', '', [])
call scalaapi#class('ScalaBeanInfo', 'scala.beans', '[c]', '', [])
