call scalaapi#package('scala.collection.script', '', '[p]', [], [])
call scalaapi#object('End', 'scala.collection.script', '[o]', ['Location', 'Product', 'Serializable'], [])
call scalaapi#class('Location', 'scala.collection.script', '[c]', [], [])
call scalaapi#trait('Message', 'scala.collection.script', '[t]', [], [])
call scalaapi#object('NoLo', 'scala.collection.script', '[o]', ['Location', 'Product', 'Serializable'], [])
call scalaapi#class('Script', 'scala.collection.script', '[c]', ['ArrayBuffer', 'Message', 'Message'], [])
call scalaapi#trait('Scriptable', 'scala.collection.script', '[t]', [], [])
call scalaapi#object('Start', 'scala.collection.script', '[o]', ['Location', 'Product', 'Serializable'], [])
